
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table tableMainLayout;

	private global::Gtk.Alignment alignmentBottom;

	private global::Gtk.Alignment alignmentTop;

	private global::Gtk.Button buttonLaunch;

	private global::Gtk.Button buttonRegister;

	private global::Gtk.Button buttonWebsite;

	private global::Gtk.CheckButton checkbuttonFullScreen;

	private global::Gtk.HBox hboxBottomLeft;

	private global::Gtk.Button button1;

	private global::Gtk.ToggleButton togglebuttonMusic;

	private global::Gtk.HBox hboxUserProperties;

	private global::Gtk.Label labelUsername;

	private global::Gtk.Entry entryUsername;

	private global::Gtk.Alignment alignmentMiddleLeft;

	private global::Gtk.Label labelPassword;

	private global::Gtk.Entry entryPassword;

	private global::Gtk.Alignment alignmentMiddleMiddle;

	private global::Gtk.Label labelMemory;

	private global::Gtk.SpinButton spinbuttonMemory;

	private global::Gtk.Alignment alignmentMiddleRight;

	private global::Gtk.Label labelNotice;

	private global::Gtk.Label labelNoticeIndicator;

	private global::Gtk.Label labelStatus;

	private global::Gtk.Label labelStatusIndicator;

	private global::Gtk.Label labelWelcome;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Modern Launcher");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.tableMainLayout = new global::Gtk.Table(((uint)(9)), ((uint)(5)), false);
		this.tableMainLayout.Name = "tableMainLayout";
		this.tableMainLayout.RowSpacing = ((uint)(6));
		this.tableMainLayout.ColumnSpacing = ((uint)(6));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.alignmentBottom = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignmentBottom.Name = "alignmentBottom";
		this.tableMainLayout.Add(this.alignmentBottom);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.alignmentBottom]));
		w1.TopAttach = ((uint)(6));
		w1.BottomAttach = ((uint)(7));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.alignmentTop = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignmentTop.Name = "alignmentTop";
		this.tableMainLayout.Add(this.alignmentTop);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.alignmentTop]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.buttonLaunch = new global::Gtk.Button();
		this.buttonLaunch.CanFocus = true;
		this.buttonLaunch.Name = "buttonLaunch";
		this.buttonLaunch.UseUnderline = true;
		this.buttonLaunch.Label = global::Mono.Unix.Catalog.GetString("Launch");
		this.tableMainLayout.Add(this.buttonLaunch);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.buttonLaunch]));
		w3.TopAttach = ((uint)(7));
		w3.BottomAttach = ((uint)(8));
		w3.LeftAttach = ((uint)(3));
		w3.RightAttach = ((uint)(4));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.buttonRegister = new global::Gtk.Button();
		this.buttonRegister.CanFocus = true;
		this.buttonRegister.Name = "buttonRegister";
		this.buttonRegister.UseUnderline = true;
		this.buttonRegister.Label = global::Mono.Unix.Catalog.GetString("Register");
		this.tableMainLayout.Add(this.buttonRegister);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.buttonRegister]));
		w4.TopAttach = ((uint)(4));
		w4.BottomAttach = ((uint)(5));
		w4.LeftAttach = ((uint)(3));
		w4.RightAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.buttonWebsite = new global::Gtk.Button();
		this.buttonWebsite.CanFocus = true;
		this.buttonWebsite.Name = "buttonWebsite";
		this.buttonWebsite.UseUnderline = true;
		this.buttonWebsite.Label = global::Mono.Unix.Catalog.GetString("Website");
		this.tableMainLayout.Add(this.buttonWebsite);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.buttonWebsite]));
		w5.TopAttach = ((uint)(5));
		w5.BottomAttach = ((uint)(6));
		w5.LeftAttach = ((uint)(3));
		w5.RightAttach = ((uint)(4));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.checkbuttonFullScreen = new global::Gtk.CheckButton();
		this.checkbuttonFullScreen.CanFocus = true;
		this.checkbuttonFullScreen.Name = "checkbuttonFullScreen";
		this.checkbuttonFullScreen.Label = global::Mono.Unix.Catalog.GetString("Full Screen");
		this.checkbuttonFullScreen.DrawIndicator = true;
		this.checkbuttonFullScreen.UseUnderline = true;
		this.tableMainLayout.Add(this.checkbuttonFullScreen);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.checkbuttonFullScreen]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(3));
		w6.RightAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.hboxBottomLeft = new global::Gtk.HBox();
		this.hboxBottomLeft.Name = "hboxBottomLeft";
		this.hboxBottomLeft.Spacing = 6;
		// Container child hboxBottomLeft.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("About");
		this.hboxBottomLeft.Add(this.button1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxBottomLeft[this.button1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hboxBottomLeft.Gtk.Box+BoxChild
		this.togglebuttonMusic = new global::Gtk.ToggleButton();
		this.togglebuttonMusic.CanFocus = true;
		this.togglebuttonMusic.Name = "togglebuttonMusic";
		this.togglebuttonMusic.UseUnderline = true;
		this.togglebuttonMusic.Active = true;
		this.togglebuttonMusic.Label = global::Mono.Unix.Catalog.GetString("Music");
		this.hboxBottomLeft.Add(this.togglebuttonMusic);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxBottomLeft[this.togglebuttonMusic]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.tableMainLayout.Add(this.hboxBottomLeft);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.hboxBottomLeft]));
		w9.TopAttach = ((uint)(7));
		w9.BottomAttach = ((uint)(8));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.hboxUserProperties = new global::Gtk.HBox();
		this.hboxUserProperties.Name = "hboxUserProperties";
		this.hboxUserProperties.Spacing = 6;
		// Container child hboxUserProperties.Gtk.Box+BoxChild
		this.labelUsername = new global::Gtk.Label();
		this.labelUsername.Name = "labelUsername";
		this.labelUsername.LabelProp = global::Mono.Unix.Catalog.GetString("Username:");
		this.hboxUserProperties.Add(this.labelUsername);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxUserProperties[this.labelUsername]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hboxUserProperties.Gtk.Box+BoxChild
		this.entryUsername = new global::Gtk.Entry();
		this.entryUsername.CanFocus = true;
		this.entryUsername.Name = "entryUsername";
		this.entryUsername.IsEditable = true;
		this.entryUsername.InvisibleChar = '•';
		this.hboxUserProperties.Add(this.entryUsername);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxUserProperties[this.entryUsername]));
		w11.Position = 1;
		// Container child hboxUserProperties.Gtk.Box+BoxChild
		this.alignmentMiddleLeft = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignmentMiddleLeft.Name = "alignmentMiddleLeft";
		this.hboxUserProperties.Add(this.alignmentMiddleLeft);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxUserProperties[this.alignmentMiddleLeft]));
		w12.Position = 2;
		// Container child hboxUserProperties.Gtk.Box+BoxChild
		this.labelPassword = new global::Gtk.Label();
		this.labelPassword.Name = "labelPassword";
		this.labelPassword.LabelProp = global::Mono.Unix.Catalog.GetString("Password:");
		this.hboxUserProperties.Add(this.labelPassword);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxUserProperties[this.labelPassword]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hboxUserProperties.Gtk.Box+BoxChild
		this.entryPassword = new global::Gtk.Entry();
		this.entryPassword.CanFocus = true;
		this.entryPassword.Name = "entryPassword";
		this.entryPassword.IsEditable = true;
		this.entryPassword.Visibility = false;
		this.entryPassword.InvisibleChar = '•';
		this.hboxUserProperties.Add(this.entryPassword);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxUserProperties[this.entryPassword]));
		w14.Position = 4;
		// Container child hboxUserProperties.Gtk.Box+BoxChild
		this.alignmentMiddleMiddle = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignmentMiddleMiddle.Name = "alignmentMiddleMiddle";
		this.hboxUserProperties.Add(this.alignmentMiddleMiddle);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxUserProperties[this.alignmentMiddleMiddle]));
		w15.Position = 5;
		// Container child hboxUserProperties.Gtk.Box+BoxChild
		this.labelMemory = new global::Gtk.Label();
		this.labelMemory.Name = "labelMemory";
		this.labelMemory.LabelProp = global::Mono.Unix.Catalog.GetString("Memory (MB):");
		this.hboxUserProperties.Add(this.labelMemory);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hboxUserProperties[this.labelMemory]));
		w16.Position = 6;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hboxUserProperties.Gtk.Box+BoxChild
		this.spinbuttonMemory = new global::Gtk.SpinButton(0D, 4096D, 64D);
		this.spinbuttonMemory.CanFocus = true;
		this.spinbuttonMemory.Name = "spinbuttonMemory";
		this.spinbuttonMemory.Adjustment.PageIncrement = 256D;
		this.spinbuttonMemory.ClimbRate = 1D;
		this.spinbuttonMemory.Numeric = true;
		this.spinbuttonMemory.Value = 1024D;
		this.hboxUserProperties.Add(this.spinbuttonMemory);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hboxUserProperties[this.spinbuttonMemory]));
		w17.Position = 7;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hboxUserProperties.Gtk.Box+BoxChild
		this.alignmentMiddleRight = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignmentMiddleRight.Name = "alignmentMiddleRight";
		this.hboxUserProperties.Add(this.alignmentMiddleRight);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hboxUserProperties[this.alignmentMiddleRight]));
		w18.Position = 8;
		this.tableMainLayout.Add(this.hboxUserProperties);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.hboxUserProperties]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		w19.LeftAttach = ((uint)(2));
		w19.RightAttach = ((uint)(3));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.labelNotice = new global::Gtk.Label();
		this.labelNotice.Name = "labelNotice";
		this.labelNotice.LabelProp = global::Mono.Unix.Catalog.GetString("Loading...");
		this.tableMainLayout.Add(this.labelNotice);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.labelNotice]));
		w20.TopAttach = ((uint)(4));
		w20.BottomAttach = ((uint)(5));
		w20.LeftAttach = ((uint)(2));
		w20.RightAttach = ((uint)(3));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.labelNoticeIndicator = new global::Gtk.Label();
		this.labelNoticeIndicator.Name = "labelNoticeIndicator";
		this.labelNoticeIndicator.Xalign = 1F;
		this.labelNoticeIndicator.LabelProp = global::Mono.Unix.Catalog.GetString("Notice:");
		this.labelNoticeIndicator.Justify = ((global::Gtk.Justification)(3));
		this.tableMainLayout.Add(this.labelNoticeIndicator);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.labelNoticeIndicator]));
		w21.TopAttach = ((uint)(4));
		w21.BottomAttach = ((uint)(5));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(0));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.labelStatus = new global::Gtk.Label();
		this.labelStatus.Name = "labelStatus";
		this.labelStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Loading...");
		this.tableMainLayout.Add(this.labelStatus);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.labelStatus]));
		w22.TopAttach = ((uint)(5));
		w22.BottomAttach = ((uint)(6));
		w22.LeftAttach = ((uint)(2));
		w22.RightAttach = ((uint)(3));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.labelStatusIndicator = new global::Gtk.Label();
		this.labelStatusIndicator.Name = "labelStatusIndicator";
		this.labelStatusIndicator.LabelProp = global::Mono.Unix.Catalog.GetString("Status:");
		this.labelStatusIndicator.Justify = ((global::Gtk.Justification)(1));
		this.tableMainLayout.Add(this.labelStatusIndicator);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.labelStatusIndicator]));
		w23.TopAttach = ((uint)(5));
		w23.BottomAttach = ((uint)(6));
		w23.LeftAttach = ((uint)(1));
		w23.RightAttach = ((uint)(2));
		w23.XOptions = ((global::Gtk.AttachOptions)(0));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.labelWelcome = new global::Gtk.Label();
		this.labelWelcome.Name = "labelWelcome";
		this.labelWelcome.LabelProp = global::Mono.Unix.Catalog.GetString("Welcome!");
		this.labelWelcome.Justify = ((global::Gtk.Justification)(2));
		this.tableMainLayout.Add(this.labelWelcome);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.labelWelcome]));
		w24.TopAttach = ((uint)(3));
		w24.BottomAttach = ((uint)(4));
		w24.LeftAttach = ((uint)(2));
		w24.RightAttach = ((uint)(3));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.tableMainLayout);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1105;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.togglebuttonMusic.Toggled += new global::System.EventHandler(this.OnTogglebuttonMusicToggled);
		this.buttonWebsite.Clicked += new global::System.EventHandler(this.OnButtonWebsiteClicked);
		this.buttonRegister.Clicked += new global::System.EventHandler(this.OnButtonRegisterClicked);
		this.buttonLaunch.Clicked += new global::System.EventHandler(this.OnButtonLaunchClicked);
	}
}
