
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table tableMainLayout;

	private global::Gtk.Alignment alignmentTop;

	private global::Gtk.Label labelWelcome;

	private global::Gtk.Button buttonAbout;

	private global::Gtk.Button buttonLaunch;

	private global::Gtk.HBox hboxSiteLinks;

	private global::Gtk.Button buttonRegister;

	private global::Gtk.Button buttonWebsite;

	private global::Gtk.Label label8;

	private global::Gtk.Label labelNotice;

	private global::Gtk.Label labelNoticeIndicator;

	private global::Gtk.Label labelStatus;

	private global::Gtk.Label labelStatusIndicator;

	private global::Gtk.Table tableUserProperties;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.Alignment alignment2;

	private global::Gtk.CheckButton checkbuttonFullScreen;

	private global::Gtk.ComboBox comboboxVersion;

	private global::Gtk.Entry entryPassword;

	private global::Gtk.Entry entryUsername;

	private global::Gtk.Label labelFullscreen;

	private global::Gtk.Label labelMemory;

	private global::Gtk.Label labelPassword;

	private global::Gtk.Label labelUsername;

	private global::Gtk.Label labelVersion;

	private global::Gtk.SpinButton spinbuttonMemory;

	private global::Gtk.ToggleButton togglebuttonMusic;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Modern Launcher");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.tableMainLayout = new global::Gtk.Table(((uint)(5)), ((uint)(7)), false);
		this.tableMainLayout.Name = "tableMainLayout";
		this.tableMainLayout.RowSpacing = ((uint)(6));
		this.tableMainLayout.ColumnSpacing = ((uint)(6));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.alignmentTop = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignmentTop.Name = "alignmentTop";
		// Container child alignmentTop.Gtk.Container+ContainerChild
		this.labelWelcome = new global::Gtk.Label();
		this.labelWelcome.Name = "labelWelcome";
		this.labelWelcome.LabelProp = global::Mono.Unix.Catalog.GetString("Welcome!");
		this.labelWelcome.Justify = ((global::Gtk.Justification)(2));
		this.alignmentTop.Add(this.labelWelcome);
		this.tableMainLayout.Add(this.alignmentTop);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.alignmentTop]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(4));
		w2.RightAttach = ((uint)(5));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.buttonAbout = new global::Gtk.Button();
		this.buttonAbout.CanFocus = true;
		this.buttonAbout.Name = "buttonAbout";
		this.buttonAbout.UseUnderline = true;
		this.buttonAbout.Label = global::Mono.Unix.Catalog.GetString("About");
		this.tableMainLayout.Add(this.buttonAbout);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.buttonAbout]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.LeftAttach = ((uint)(5));
		w3.RightAttach = ((uint)(6));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.buttonLaunch = new global::Gtk.Button();
		this.buttonLaunch.CanFocus = true;
		this.buttonLaunch.Name = "buttonLaunch";
		this.buttonLaunch.UseUnderline = true;
		this.buttonLaunch.Label = global::Mono.Unix.Catalog.GetString("Launch");
		this.tableMainLayout.Add(this.buttonLaunch);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.buttonLaunch]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.hboxSiteLinks = new global::Gtk.HBox();
		this.hboxSiteLinks.Name = "hboxSiteLinks";
		this.hboxSiteLinks.Spacing = 6;
		// Container child hboxSiteLinks.Gtk.Box+BoxChild
		this.buttonRegister = new global::Gtk.Button();
		this.buttonRegister.CanFocus = true;
		this.buttonRegister.Name = "buttonRegister";
		this.buttonRegister.UseUnderline = true;
		this.buttonRegister.Label = global::Mono.Unix.Catalog.GetString("Register");
		this.hboxSiteLinks.Add(this.buttonRegister);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxSiteLinks[this.buttonRegister]));
		w5.Position = 0;
		// Container child hboxSiteLinks.Gtk.Box+BoxChild
		this.buttonWebsite = new global::Gtk.Button();
		this.buttonWebsite.CanFocus = true;
		this.buttonWebsite.Name = "buttonWebsite";
		this.buttonWebsite.UseUnderline = true;
		this.buttonWebsite.Label = global::Mono.Unix.Catalog.GetString("Website");
		this.hboxSiteLinks.Add(this.buttonWebsite);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxSiteLinks[this.buttonWebsite]));
		w6.Position = 1;
		this.tableMainLayout.Add(this.hboxSiteLinks);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.hboxSiteLinks]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Minecraft Vast-Light");
		this.tableMainLayout.Add(this.label8);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.label8]));
		w8.LeftAttach = ((uint)(4));
		w8.RightAttach = ((uint)(5));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.labelNotice = new global::Gtk.Label();
		this.labelNotice.Name = "labelNotice";
		this.labelNotice.LabelProp = global::Mono.Unix.Catalog.GetString("Loading...");
		this.tableMainLayout.Add(this.labelNotice);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.labelNotice]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(4));
		w9.RightAttach = ((uint)(5));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.labelNoticeIndicator = new global::Gtk.Label();
		this.labelNoticeIndicator.Name = "labelNoticeIndicator";
		this.labelNoticeIndicator.Xalign = 1F;
		this.labelNoticeIndicator.LabelProp = global::Mono.Unix.Catalog.GetString("Notice:");
		this.labelNoticeIndicator.Justify = ((global::Gtk.Justification)(3));
		this.tableMainLayout.Add(this.labelNoticeIndicator);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.labelNoticeIndicator]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(3));
		w10.RightAttach = ((uint)(4));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.labelStatus = new global::Gtk.Label();
		this.labelStatus.Name = "labelStatus";
		this.labelStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Loading...");
		this.tableMainLayout.Add(this.labelStatus);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.labelStatus]));
		w11.TopAttach = ((uint)(3));
		w11.BottomAttach = ((uint)(4));
		w11.LeftAttach = ((uint)(4));
		w11.RightAttach = ((uint)(5));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.labelStatusIndicator = new global::Gtk.Label();
		this.labelStatusIndicator.Name = "labelStatusIndicator";
		this.labelStatusIndicator.LabelProp = global::Mono.Unix.Catalog.GetString("Status:");
		this.labelStatusIndicator.Justify = ((global::Gtk.Justification)(1));
		this.tableMainLayout.Add(this.labelStatusIndicator);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.labelStatusIndicator]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.LeftAttach = ((uint)(3));
		w12.RightAttach = ((uint)(4));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.tableUserProperties = new global::Gtk.Table(((uint)(7)), ((uint)(2)), false);
		this.tableUserProperties.Name = "tableUserProperties";
		this.tableUserProperties.RowSpacing = ((uint)(6));
		this.tableUserProperties.ColumnSpacing = ((uint)(6));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.tableUserProperties.Add(this.alignment1);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.alignment1]));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.tableUserProperties.Add(this.alignment2);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.alignment2]));
		w14.TopAttach = ((uint)(6));
		w14.BottomAttach = ((uint)(7));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.checkbuttonFullScreen = new global::Gtk.CheckButton();
		this.checkbuttonFullScreen.CanFocus = true;
		this.checkbuttonFullScreen.Name = "checkbuttonFullScreen";
		this.checkbuttonFullScreen.Label = "";
		this.checkbuttonFullScreen.DrawIndicator = true;
		this.checkbuttonFullScreen.UseUnderline = true;
		this.tableUserProperties.Add(this.checkbuttonFullScreen);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.checkbuttonFullScreen]));
		w15.TopAttach = ((uint)(4));
		w15.BottomAttach = ((uint)(5));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.comboboxVersion = global::Gtk.ComboBox.NewText();
		this.comboboxVersion.Name = "comboboxVersion";
		this.tableUserProperties.Add(this.comboboxVersion);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.comboboxVersion]));
		w16.TopAttach = ((uint)(5));
		w16.BottomAttach = ((uint)(6));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.entryPassword = new global::Gtk.Entry();
		this.entryPassword.CanFocus = true;
		this.entryPassword.Name = "entryPassword";
		this.entryPassword.IsEditable = true;
		this.entryPassword.Visibility = false;
		this.entryPassword.InvisibleChar = '•';
		this.tableUserProperties.Add(this.entryPassword);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.entryPassword]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.entryUsername = new global::Gtk.Entry();
		this.entryUsername.CanFocus = true;
		this.entryUsername.Name = "entryUsername";
		this.entryUsername.IsEditable = true;
		this.entryUsername.InvisibleChar = '•';
		this.tableUserProperties.Add(this.entryUsername);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.entryUsername]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.labelFullscreen = new global::Gtk.Label();
		this.labelFullscreen.Name = "labelFullscreen";
		this.labelFullscreen.LabelProp = global::Mono.Unix.Catalog.GetString("Fullscreen:");
		this.tableUserProperties.Add(this.labelFullscreen);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.labelFullscreen]));
		w19.TopAttach = ((uint)(4));
		w19.BottomAttach = ((uint)(5));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.labelMemory = new global::Gtk.Label();
		this.labelMemory.Name = "labelMemory";
		this.labelMemory.LabelProp = global::Mono.Unix.Catalog.GetString("Memory (MB):");
		this.tableUserProperties.Add(this.labelMemory);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.labelMemory]));
		w20.TopAttach = ((uint)(3));
		w20.BottomAttach = ((uint)(4));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.labelPassword = new global::Gtk.Label();
		this.labelPassword.Name = "labelPassword";
		this.labelPassword.LabelProp = global::Mono.Unix.Catalog.GetString("Password:");
		this.tableUserProperties.Add(this.labelPassword);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.labelPassword]));
		w21.TopAttach = ((uint)(2));
		w21.BottomAttach = ((uint)(3));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.labelUsername = new global::Gtk.Label();
		this.labelUsername.Name = "labelUsername";
		this.labelUsername.LabelProp = global::Mono.Unix.Catalog.GetString("Username:");
		this.tableUserProperties.Add(this.labelUsername);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.labelUsername]));
		w22.TopAttach = ((uint)(1));
		w22.BottomAttach = ((uint)(2));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.labelVersion = new global::Gtk.Label();
		this.labelVersion.Name = "labelVersion";
		this.labelVersion.LabelProp = global::Mono.Unix.Catalog.GetString("Version:");
		this.tableUserProperties.Add(this.labelVersion);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.labelVersion]));
		w23.TopAttach = ((uint)(5));
		w23.BottomAttach = ((uint)(6));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableUserProperties.Gtk.Table+TableChild
		this.spinbuttonMemory = new global::Gtk.SpinButton(0D, 4096D, 64D);
		this.spinbuttonMemory.CanFocus = true;
		this.spinbuttonMemory.Name = "spinbuttonMemory";
		this.spinbuttonMemory.Adjustment.PageIncrement = 256D;
		this.spinbuttonMemory.ClimbRate = 1D;
		this.spinbuttonMemory.Numeric = true;
		this.spinbuttonMemory.Value = 1024D;
		this.tableUserProperties.Add(this.spinbuttonMemory);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tableUserProperties[this.spinbuttonMemory]));
		w24.TopAttach = ((uint)(3));
		w24.BottomAttach = ((uint)(4));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		this.tableMainLayout.Add(this.tableUserProperties);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.tableUserProperties]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.LeftAttach = ((uint)(1));
		w25.RightAttach = ((uint)(2));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMainLayout.Gtk.Table+TableChild
		this.togglebuttonMusic = new global::Gtk.ToggleButton();
		this.togglebuttonMusic.CanFocus = true;
		this.togglebuttonMusic.Name = "togglebuttonMusic";
		this.togglebuttonMusic.UseUnderline = true;
		this.togglebuttonMusic.Active = true;
		this.togglebuttonMusic.Label = global::Mono.Unix.Catalog.GetString("Music");
		this.tableMainLayout.Add(this.togglebuttonMusic);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.tableMainLayout[this.togglebuttonMusic]));
		w26.TopAttach = ((uint)(3));
		w26.BottomAttach = ((uint)(4));
		w26.LeftAttach = ((uint)(5));
		w26.RightAttach = ((uint)(6));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.tableMainLayout);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1105;
		this.DefaultHeight = 350;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.togglebuttonMusic.Toggled += new global::System.EventHandler(this.OnTogglebuttonMusicToggled);
		this.buttonRegister.Clicked += new global::System.EventHandler(this.OnButtonRegisterClicked);
		this.buttonWebsite.Clicked += new global::System.EventHandler(this.OnButtonWebsiteClicked);
		this.buttonLaunch.Clicked += new global::System.EventHandler(this.OnButtonLaunchClicked);
		this.buttonAbout.Clicked += new global::System.EventHandler(this.OnButtonAboutClicked);
	}
}
