
// This file has been generated by the GUI designer. Do not modify.
namespace ModernLauncher
{
	public partial class AboutDialog
	{
		private global::Gtk.VBox vboxMain;

		private global::Gtk.Image imageLogo;

		private global::Gtk.Label labelTitle;

		private global::Gtk.Label labelVersion;

		private global::Gtk.Label labelDescription;

		private global::Gtk.Label labelWebsite;

		private global::Gtk.Label labelCopyright;

		private global::Gtk.Label labelLicense;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ModernLauncher.AboutDialog
			this.Name = "ModernLauncher.AboutDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("About");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child ModernLauncher.AboutDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "AboutDialog_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child AboutDialog_VBox.Gtk.Box+BoxChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.imageLogo = new global::Gtk.Image();
			this.imageLogo.Name = "imageLogo";
			this.vboxMain.Add(this.imageLogo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.imageLogo]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.labelTitle = new global::Gtk.Label();
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Modern Launcher Minecraft</b>");
			this.labelTitle.UseMarkup = true;
			this.vboxMain.Add(this.labelTitle);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.labelTitle]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.labelVersion = new global::Gtk.Label();
			this.labelVersion.Name = "labelVersion";
			this.labelVersion.LabelProp = global::Mono.Unix.Catalog.GetString("Loading...");
			this.vboxMain.Add(this.labelVersion);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.labelVersion]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.labelDescription = new global::Gtk.Label();
			this.labelDescription.Name = "labelDescription";
			this.labelDescription.LabelProp = global::Mono.Unix.Catalog.GetString("A part of <b>Modern Minecraft</b> project which helps people to launch Minecraft " +
					"in a lighter and more convenient way.");
			this.labelDescription.UseMarkup = true;
			this.labelDescription.Wrap = true;
			this.labelDescription.Justify = ((global::Gtk.Justification)(2));
			this.vboxMain.Add(this.labelDescription);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.labelDescription]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.labelWebsite = new global::Gtk.Label();
			this.labelWebsite.Name = "labelWebsite";
			this.labelWebsite.LabelProp = global::Mono.Unix.Catalog.GetString("<a href=\"https://github.com/CrystalStu/ModernMinecraft\">Website</a>");
			this.labelWebsite.UseMarkup = true;
			this.vboxMain.Add(this.labelWebsite);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.labelWebsite]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.labelCopyright = new global::Gtk.Label();
			this.labelCopyright.Name = "labelCopyright";
			this.labelCopyright.LabelProp = global::Mono.Unix.Catalog.GetString("Copyright © 2017-2019 Crystal Computer Studio\nCopyright © 2017-2019 Minecraft QUA" +
					"RTZ Studio\nCopyright © 2017-2019 TURX");
			this.labelCopyright.UseMarkup = true;
			this.labelCopyright.Justify = ((global::Gtk.Justification)(2));
			this.vboxMain.Add(this.labelCopyright);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.labelCopyright]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.labelLicense = new global::Gtk.Label();
			this.labelLicense.Name = "labelLicense";
			this.labelLicense.LabelProp = global::Mono.Unix.Catalog.GetString("Distributed with <i>GNU General Public License v3.0</i>.");
			this.labelLicense.UseMarkup = true;
			this.vboxMain.Add(this.labelLicense);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.labelLicense]));
			w8.Position = 6;
			w8.Expand = false;
			w8.Fill = false;
			w1.Add(this.vboxMain);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1[this.vboxMain]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child ModernLauncher.AboutDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "AboutDialog_ActionArea";
			// Container child AboutDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonOk]));
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 406;
			this.DefaultHeight = 358;
			this.Show();
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
